apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-health-service
  labels:
    app: test-health-service
    version: 1.0.0
spec:
  replicas: 3
  selector:
    matchLabels:
      app: test-health-service
  template:
    metadata:
      labels:
        app: test-health-service
        version: 1.0.0
    spec:
      containers:
      - name: test-health-service
        image: test-health-service:1.0.0
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: PORT
          value: "8080"
        - name: VERSION
          value: 1.0.0
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /health/live
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /health/startup
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 30
      restartPolicy: Always
