apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: demo-enterprise
  labels:
    app: demo-enterprise
spec:
  selector:
    matchLabels:
      app: demo-enterprise
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s
