version: '3.8'

services:
  demo-enterprise:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - VERSION=1.0.0
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
    restart: unless-stopped
    networks:
      - health-network

networks:
  health-network:
    driver: bridge
