apiVersion: v1
kind: Service
metadata:
  name: {{.Config.Name}}
  labels:
    app: {{.Config.Name}}
spec:
  selector:
    app: {{.Config.Name}}
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
