# Development Environment Configuration
environment: development

server:
  host: "0.0.0.0"
  port: 8080
  read_timeout: 30s
  write_timeout: 30s
  idle_timeout: 60s

# Security settings for development
security:
  mtls:
    enabled: false  # Disabled for easier development
    cert_file: ""
    key_file: ""
    ca_file: ""
    client_auth: "NoClientCert"
  
  rbac:
    enabled: true
    policy_file: "configs/rbac-dev.json"
    default_role: "admin"  # Permissive for development
  
  audit:
    enabled: true
    log_file: "logs/audit-dev.log"
    level: "info"

# Database/Dependencies
dependencies:
  database:
    enabled: false  # Use in-memory for development
    connection_string: ""
    max_connections: 10
    timeout: 5s
  
  redis:
    enabled: false
    address: "localhost:6379"
    password: ""
    db: 0

# Observability
observability:
  metrics:
    enabled: true
    path: "/metrics"
    
  tracing:
    enabled: true
    endpoint: "http://localhost:14268/api/traces"
    service_name: "{{.ServiceName}}-dev"
    
  logging:
    level: "debug"
    format: "json"
    output: "stdout"

# Health check configuration
health:
  check_interval: 30s
  timeout: 5s
  
# CloudEvents
cloudevents:
  enabled: true
  source: "{{.ServiceName}}/dev"
  sink: "http://localhost:8081/events"

# Development-specific settings
development:
  hot_reload: true
  debug_mode: true
  cors_enabled: true
  allowed_origins: ["*"]
